### ISSUE TITLE
invalid JSON response when adding [w4os_profile] shortcode element

### ISSUE THREAD

**Issue by jjamesk** [GuduleLapointe/w4os#10]
Wordpress plugin: W4OS OpenSimulator Interface
version: Version 1.2.9 
Issue: created a new wordpress page, added the "short code" element then added "[w4os_profile]", wordpress errors with "Updating failed. The response is not a valid JSON response."

**Comment by GuduleLapointe** [comment]
Thank you for this report, James. It is fixed in 1.2.10.
