### ISSUE TITLE
Grid Account Creation

### ISSUE THREAD

**Issue by jjamesk** [GuduleLapointe/w4os#11]
Wordpress plugin: W4OS OpenSimulator Interface
version: Version 1.2.10
Section: w4os_profile

When attempted to create grid account with the [w4os_profile] shortcodes embedded, I set the new account first name, surname and password then press "save" then it errors with "Wrong password"

![w4os_profile](https://user-images.githubusercontent.com/44103393/134562253-a07a3ced-dcf8-405f-956d-947ac6c777ed.jpg)

**Comment by GuduleLapointe** [comment]
The password has to be the same as your WP account password, is it the case?

**Comment by jjamesk** [comment]
> The password has to be the same as your WP account password, is it the case?

I have just tested creating user "tester monkey" with the same password as the WP admin but i get "Could not insert the user".
does the WP user have to be the same as the user you are creating in the grid ?

**Comment by GuduleLapointe** [comment]
Indeed. The error message is misleading.

Some situations occurring when the grid is new were not handled correctly. The user is actually created, but some of the following steps fail (like setting home region when no default is set or trying to apply model when no one was created).
I think I fixed it, and made more accurate error messages.

Please note that in your first attempt, "Test" is a reserved word and cannot be used in names from the website (like "Admin" and "Default"). If you need such users you have to create them from console.

**Comment by jjamesk** [comment]
Hi, yes i found out that the "Test" name is reserved :), if you release a new version of the pluigin i can test it.

Thank you again for your support :)

**Comment by GuduleLapointe** [comment]
The change are published in this repo, I will make a release for automatic update soon.
