### ISSUE TITLE
Database check fails if mysql is case sensitive

### ISSUE THREAD

**Issue by magicoli** [GuduleLapointe/w4os#2]
fixed in 97a66253

**Comment by GuduleLapointe** [comment]
Some mysql distributions are case-sensitive. This plugin deals with both situations, but in some rare cases you might get a database connection error (when restoring a db backup on a new server, for example). However this would be the sign of a bigger problem, so this specific case is not covered in this W4OS.

MySQL table names are case-insensitive on Windows and case-sensitive on Linux by default.
This can be overridden in mysql server config:

`[mysqld]
lower_case_table_names=1`

If, by any chance, you created your Robust server while this option is active, and create a backup to restore it on a case-sensitive server, all table will have lowercase names and won't be useable (not only by W40S but also by OpenSimulator itself). Applying this setting on the new server is a valid workaround, but the best practice would be to rename all tables originally according to their original names (be careful: not all OpenSimulator tables are using upper cases).

Here are the default Robust table names, with their "normal" cases:

- AgentPrefs
- assets
- auth
- Avatars
- Friends
- GridUser
- inventoryfolders
- inventoryitems
- migrations
- MuteList
- Presence
- regions
- tokens
- UserAccounts
