### ISSUE TITLE
Regression: new avatar not synced automatically, and not displayed on shortcode

### ISSUE THREAD

**Issue by GuduleLapointe** [GuduleLapointe/w4os#26]
A regression appeared somewhere between 2.1 release and today,.. It affects only dev version as 2.1 is still  the latest official release.

- avatar create (from profile page) sucessfull, but reference (w4os_uuid meta) is not updated, so the form still appears instead of profile
- when manually updated, the profile is empty

Both used to work on 2.1, so something went wrong in one of the 110 commits since then... Let's find what happened

**Comment by magicoli** [comment]
fixed in 7e71d1647c93b528df9a2bdea3b7595a73211e04
