### ISSUE TITLE
Add grid stats text output for external scrapers

### ISSUE THREAD

**Issue by magicoli** [GuduleLapointe/w4os#59]
Grid stats text output for external scrapers like Hypergrid Business

https://www.hypergridbusiness.com/faq/how-and-why-to-set-up-a-stats-page/

The main things are:

The less formatting, the better.

I'd like the following data points:

    Total standard regions, or total land area in square meters.
    Total visitors, combined total of local and hypergrid
    Total registered users

Some grids also like to break out named regions, or list local visitors and hypergrid visitors separately. That's fine if they're in addition to the three stats above. If they're instead of the three stats above, then the grids suffer because the named regions are always going to be a lower count than standard region equivalents, and only showing local visitors will be a lower count than the combined total of both. (If I have to manually find and add up numbers then it slows down the stats collection, and creates more chances for mistakes.)

**Comment by GuduleLapointe** [comment]
Not enough needs currently
