### ISSUE TITLE
Create multiple avatars with a single mail address

### ISSUE THREAD

**Issue by GuduleLapointe** [GuduleLapointe/w4os#62]
Avatar and WP accounts are linked by email address, so only one avatar can be created with a single mail address.

Would it be possible (and desirable) to allow several avatars with the same mail address?

(question submitted via the website)

**Comment by GuduleLapointe** [comment]
Yes, indeed. It is not only a w4os limitation, though, it's designed this way on most web interfaces (including SL!).

The question is interesting, enabling several grid accounts could  be possible, and while I am not sure that it is a good idea to encourage users to create alts too easily, it might be a way to better figure the number of actual users.

Currently, avatar info are stored directly in the WP user metadata, so it would require a couple of changes to link a WP user to several avatars, but I don't see why it wouldn't be possible.

The main question is: would it be a good idea?

**Comment by GuduleLapointe** [comment]
BTW, there is an easy workaround, thanks to the "+" standard mail feature: on any mail address, you can include "+some.random-text" just before the @ sign, it behaves as a mail alias.

For example, if your mail address is user@example.org:

    mails sent to user+Avatar.One@example.org
    or user+Avatar.Two@example.org

    should both be sent to user@example.org

    (without any need to configure it, nor in your mail software, nor in your mail provider account)

So you can use this feature to create several accounts without creating new mail addresses (and this is valid on quite all platforms/websites/softwares requiring an "unique" mail address per account)

**Comment by GuduleLapointe** [comment]
Actually, as it *is* possible from the console to create several avatars with the same email address, w4os shouldn't rely on this uniqueness anyway, it could create unpredictable situations.

So, whether allowing multiple avies or not, the current linking method is probably an issue.

**Comment by scatterp2** [comment]
as the only current open issue marked bug is there any resolution planned timeline eta ?

**Comment by GuduleLapointe** [comment]
> as the only current open issue marked bug is there any resolution planned timeline eta ?

Unfortunately no, not currently. It is a bug indeed, but its resolution requires modifying parts of code at different levels, which means testing again most of the currently verified features, so it is difficult to make an estimation.

As soon as we get something stable enough for testing, it will be published in this repository, prior to release.

**Comment by GuduleLapointe** [comment]
The issue is currently worked on in [branch 3.x-dev](https://github.com/GuduleLapointe/w4os/tree/3.x-dev)

**BRANCH 3.x-dev IS NOT READY FOR LIVE GRIDS**, but if you have a test simulator, you can have a sneak peek on what's coming and comment...

Currently, the avatar synchronization, compatible with multiple avatars sharing a mail account, is implemented.

Front end avatar registration is not yet adapted and still use the legacy behavior, so there may be conflicts until the full transition is finished.

**Comment by magicoli** [comment]
The functionalty was added in 60fa3460eb2cdef043584621108088067ae7074e of [branch 3.x-dev](https://github.com/GuduleLapointe/w4os/tree/3.x-dev)

**BRANCH 3.x-dev IS NOT READY FOR LIVE GRIDS**, but the concept is working.

> The issue is currently worked on in [branch 3.x-dev](https://github.com/GuduleLapointe/w4os/tree/3.x-dev)
> 
> **BRANCH 3.x-dev IS NOT READY FOR LIVE GRIDS**, but if you have a test simulator, you can have a sneak peek on what's coming and comment...
> 
> Currently, the avatar synchronization, compatible with multiple avatars sharing a mail account, is implemented.
> 
> Front end avatar registration is not yet adapted and still use the legacy behavior, so there may be conflicts until the full transition is finished.
