### ISSUE TITLE
"w4os - OpenSimulator Web Interface" casuing wordpress pages to fail loading

### ISSUE THREAD

**Issue by jjamesk** [GuduleLapointe/w4os#64]
Hello Gudule

I am revisiting the "w4os - OpenSimulator Web Interface" wordpress plugin using wordpress Version 6.0.2, when the plugin is activated and configured wordpress pages stop rending and just show a white page, when you view the source of the page it seems to stop rendering the page just before the body tag.

I've taken a couple of screenshots for you

![configinfo](https://user-images.githubusercontent.com/44103393/192066227-ae196501-4cbe-4566-8323-01973cf0e1d2.jpg)
![pagefail](https://user-images.githubusercontent.com/44103393/192066241-289320df-a9f3-4081-8d72-585d080b4f09.jpg)

**Comment by GuduleLapointe** [comment]
Thanks for the reporting.

Your screenshot show no db name and user, did you hide them for safety purpose or did you forget to fill them? The site should not crash, but the plugin won't work properly with wrong or missing database credentials.

That said, the screenshot is not really helpful, can you get the error message from your webserver log file? Also, which version of the plugin is installed?

I will work on this anyway, but it would be easier with more info.

**Comment by jjamesk** [comment]
Hi Gudule

The  db name and user were hidden for safety purposes. Looking at the Apache error log it looks like the userprofile table is missing which is possibly due to me forgetting to enable user profiles in the opensim config (i am an idiot), will review this and retest, thank you as always for your support.

**Comment by GuduleLapointe** [comment]
Oh OK, that explained why I couldn't reproduce the error... 
Nevertheless, I will add some more checls to make sure it doesn't crash the website and a comprehensive error is displayed.

**Comment by jjamesk** [comment]
Hi Gudule

I fixed the userprofile table issue but that may have been a red herring.

Just to confirm that i am using Wordpress Version 6.0.2 and w4os - OpenSimulator Web Interface Version 2.3.7

i've attached a clean copy of the appache error log

[error.log](https://github.com/GuduleLapointe/w4os/files/9638381/error.log)

**Comment by jjamesk** [comment]
updated to Version 2.3.9 same issue with pages loading blank, attached clean Apache error log
[error.log](https://github.com/GuduleLapointe/w4os/files/9639443/error.log)

**Comment by GuduleLapointe** [comment]
> updated to Version 2.3.9 same issue with pages loading blank, attached clean Apache error log [error.log](https://github.com/GuduleLapointe/w4os/files/9639443/error.log)

Actually it is not the same issue (even if the result seems the same), while initial issue was indeed triggered by w4os, this time the crash is raised during wp template processing and w4os does not appear in the function call history. This makes it very difficult to figure what's going on.

There are some questions that might help me to narrow down:

- are all public pages blank or only some and which ones?
- which theme are you using? 
- is your opensim grid up and running?

There are some tricks which might help to track the problem:

- test with another theme (one of default WP themes, preferably)
- test with all other plugins disabled
- test with all w4os options disabled

If one of the 2 last tests fix the crash, you can try re-enabling one by one the plugins or the w4os options so we can narrow down the search.

BTW, it comes from the theme or another plugin, it might be a compatibility issue that I could solve in w4os.

```
[Sat Sep 24 21:31:30.178936 2022] [php:error] [pid 1030166] [client 90.247.233.188:1673] PHP Fatal error:  Uncaught TypeError: array_unique(): Argument #1 ($array) must be of type array, null given in /var/www/html3/wp-includes/post-template.php:838
Stack trace:
#0 /var/www/html3/wp-includes/post-template.php(838): array_unique()
#1 /var/www/html3/wp-includes/post-template.php(595): get_body_class()
#2 /var/www/html3/wp-includes/template-canvas.php(20): body_class()
#3 /var/www/html3/wp-includes/template-loader.php(106): include('...')
#4 /var/www/html3/wp-blog-header.php(19): require_once('...')
#5 /var/www/html3/index.php(17): require('...')
#6 {main}
  thrown in /var/www/html3/wp-includes/post-template.php on line 838
```

**Comment by jjamesk** [comment]
If i go to https://jakeygrid.gotdns.com/index.php/2022/09/23/hello-world/ it states "There has been a critical error on this website."  if i disable your plugin then the page loads, I have only 1 other plugin installed and when i disable that, the error still occurs 

Theme is the default "Twenty Twenty-TwoVersion: 1.2"

Yes the opensim grid up and running, it is hosted on an external server in Germany  and I am accessing it via the external IP from the UK and run the grid client from my PC in the UK.

If it is helpful we could arrange a screen sharing session using discord

**Comment by GuduleLapointe** [comment]
I still need more context. I tried to reproduce the issue but could not. 
Could you tell me the PHP and OpenSimulator versions?

I noticed the minimum requirement for PHP was documented as 5.6 or later, which is wrong. Supported version are from 7.3 to 8.1, I will fix that information in the next release.

**Comment by jjamesk** [comment]
Hi

PHP 8.1.9
OpenSim 0.9.2.2 Yeti Dev

**Comment by magicoli** [comment]
I tested the plugin with PHP 8.1.2 and 8.1.10 (amongst other ones) and I got no issue, so PHP is not to blame.

Unfortunately, I still can't reproduce your bug. Maybe we should arrange a screen share, as you suggested (although I don't use discord). You can contact me in private for that.
