### ISSUE TITLE
Web assets server slug does not appear in permalink settings page until helpers settings page is saved

### ISSUE THREAD

**Issue by magicoli** [GuduleLapointe/w4os#65]
The assets slug does not appear in permalink settings until the w4os helpers settings page is saved (with assets server enabled of course).

This is a confusing little bug: web assets server should either appear disabled by default, either be fully enabled on new installations, including in permalink settings page. 

The web assets server itself is most certainly not enabled either until the helpers setting page is saved (but I didn't try it on a fresh new installation).

**Comment by GuduleLapointe** [comment]
Fixed a long time ago, in 10d705e717c0d2f2a3da22f4b45e1e46a4ca54b8
