### ISSUE TITLE
Helpers query.php problems

### ISSUE THREAD

**Issue by lefterists** [GuduleLapointe/w4os#68]
1) Null/zero return values are not handled properly in almost all queries

2) Seems like some queries are executed multiple times, null or not results

03:58:02 - [LLCLIENTVIEW]: Caught exception while processing DirClassifiedQuery for Test User: Object reference not set to an instance of an object.
03:58:03 - [LLCLIENTVIEW]: Caught exception while processing DirClassifiedQuery for Test User: Object reference not set to an instance of an object.
03:58:03 - [LLCLIENTVIEW]: Caught exception while processing DirClassifiedQuery for Test User: Object reference not set to an instance of an object.
03:58:21 - [LLCLIENTVIEW]: Caught exception while processing DirLandQuery for Test User: Object reference not set to an instance of an object.
03:58:31 - [LLCLIENTVIEW]: Caught exception while processing DirPlacesQuery for Test User: Object reference not set to an instance of an object.
03:58:31 - [LLCLIENTVIEW]: Caught exception while processing DirPlacesQuery for Test User: Object reference not set to an instance of an object.
03:58:31 - [LLCLIENTVIEW]: Caught exception while processing DirPlacesQuery for Test User: Object reference not set to an instance of an object.

**Comment by GuduleLapointe** [comment]
The duplicate queries seem to come from the way the viewer handles search. I already noticed it and couldn't find something causing this inside the helpers code.

I will have a look on null values

**Comment by GuduleLapointe** [comment]
I  could not reproduce the NULL/Zero issue, could you tell me how you got this behaviour?

> 1. Null/zero return values are not handled properly in almost all queries

**Comment by lefterists** [comment]
Must be the modules that I am using then. I am compiling and using the dotnet6 OpenSim 0,9.3 and the corresponding modules for it.
