### ISSUE TITLE
Activating plugin lags and causes the whole site to slow way down

### ISSUE THREAD

**Issue by GuduleLapointe** [GuduleLapointe/w4os#80]
I installed this latest version and have the slow-to-activate issue and after activation, the whole Wordpress is slow. Here are error logs:

1 | PHP Deprecated | Optional parameter $content declared before required parameter $function_name is implicitly treated as a required parameterPlugin: w4os - OpenSimulator Web InterfaceFile: /wp-content/plugins/w4os-opensimulator-web-interface/blocks/web-search.phpLine: 342 | Aug 12, 2024 - 03:00:51(1 occurrence logged)
-- | -- | -- | --
2 | PHP Deprecated | Optional parameter $content declared before required parameter $function_name is implicitly treated as a required parameterPlugin: w4os - OpenSimulator Web InterfaceFile: /wp-content/plugins/w4os-opensimulator-web-interface/blocks/popular-places.phpLine: 318 | Aug 12, 2024 - 03:00:51(1 occurrence logged)
3 | PHP Deprecated | Optional parameter $content declared before required parameter $function_name is implicitly treated as a required parameterPlugin: w4os - OpenSimulator Web InterfaceFile: /wp-content/plugins/w4os-opensimulator-web-interface/blocks/avatar-profile.phpLine: 265 | Aug 12, 2024 - 03:00:51(1 occurrence logged)
4 | PHP Deprecated | Optional parameter $content declared before required parameter $function_name is implicitly treated as a required parameterPlugin: w4os - OpenSimulator Web InterfaceFile: /wp-content/plugins/w4os-opensimulator-web-interface/blocks/grid-status.phpLine: 202 | Aug 12, 2024 - 03:00:51(1 occurrence logged)
5 | PHP Deprecated | Optional parameter $content declared before required parameter $function_name is implicitly treated as a required parameterPlugin: w4os - OpenSimulator Web InterfaceFile: /wp-content/plugins/w4os-opensimulator-web-interface/blocks/grid-info.phpLine: 250 | Aug 12, 2024 - 03:00:51(1 occurrence logged)
6 | Other | Cron reschedule event error for hook: action_scheduler_run_queue, Error code: invalid_schedule, Error message: Event schedule does not exist., Data: {"schedule":"every_minute","args":["WP Cron"],"interval":60} | Aug 12, 2024 - 02:59:22(1 occurrence logged)

</body>
</html>1	PHP Deprecated	Optional parameter $content declared before required parameter $function_name is implicitly treated as a required parameter
Plugin: [w4os - OpenSimulator Web Interface](https://w4os.org/)
File: [/wp-content/plugins/w4os-opensimulator-web-interface/blocks/web-search.php](https://nvwdev.masalaestates.net/wp-admin/plugin-editor.php?file=w4os-opensimulator-web-interface%2Fblocks%2Fweb-search.php&plugin=w4os-opensimulator-web-interface%2Fw4os.php)
Line: 342	Aug 12, 2024 - 03:00:51
(1 occurrence logged)
2	PHP Deprecated	Optional parameter $content declared before required parameter $function_name is implicitly treated as a required parameter
Plugin: [w4os - OpenSimulator Web Interface](https://w4os.org/)
File: [/wp-content/plugins/w4os-opensimulator-web-interface/blocks/popular-places.php](https://nvwdev.masalaestates.net/wp-admin/plugin-editor.php?file=w4os-opensimulator-web-interface%2Fblocks%2Fpopular-places.php&plugin=w4os-opensimulator-web-interface%2Fw4os.php)
Line: 318	Aug 12, 2024 - 03:00:51
(1 occurrence logged)
3	PHP Deprecated	Optional parameter $content declared before required parameter $function_name is implicitly treated as a required parameter
Plugin: [w4os - OpenSimulator Web Interface](https://w4os.org/)
File: [/wp-content/plugins/w4os-opensimulator-web-interface/blocks/avatar-profile.php](https://nvwdev.masalaestates.net/wp-admin/plugin-editor.php?file=w4os-opensimulator-web-interface%2Fblocks%2Favatar-profile.php&plugin=w4os-opensimulator-web-interface%2Fw4os.php)
Line: 265	Aug 12, 2024 - 03:00:51
(1 occurrence logged)
4	PHP Deprecated	Optional parameter $content declared before required parameter $function_name is implicitly treated as a required parameter
Plugin: [w4os - OpenSimulator Web Interface](https://w4os.org/)
File: [/wp-content/plugins/w4os-opensimulator-web-interface/blocks/grid-status.php](https://nvwdev.masalaestates.net/wp-admin/plugin-editor.php?file=w4os-opensimulator-web-interface%2Fblocks%2Fgrid-status.php&plugin=w4os-opensimulator-web-interface%2Fw4os.php)
Line: 202	Aug 12, 2024 - 03:00:51
(1 occurrence logged)
5	PHP Deprecated	Optional parameter $content declared before required parameter $function_name is implicitly treated as a required parameter
Plugin: [w4os - OpenSimulator Web Interface](https://w4os.org/)
File: [/wp-content/plugins/w4os-opensimulator-web-interface/blocks/grid-info.php](https://nvwdev.masalaestates.net/wp-admin/plugin-editor.php?file=w4os-opensimulator-web-interface%2Fblocks%2Fgrid-info.php&plugin=w4os-opensimulator-web-interface%2Fw4os.php)
Line: 250	Aug 12, 2024 - 03:00:51
(1 occurrence logged)
6	Other	Cron reschedule event error for hook: action_scheduler_run_queue, Error code: invalid_schedule, Error message: Event schedule does not exist., Data: {"schedule":"every_minute","args":["WP Cron"],"interval":60}	Aug 12, 2024 - 02:59:22
(1 occurrence logged)

_Originally posted by @mteedev in https://github.com/GuduleLapointe/w4os/discussions/78#discussioncomment-10312334_

**Comment by mteedev** [comment]
Thank you! We've restructured things a good bit and I redid the Permalinks. Things seem a bit better. Thank you for the update!
